// let b = 2;

try {
  let a = 2 + b;
} catch (erro) {
  console.log(erro);
  // throw new Error(erro);
}

console.log("Teste");
