let b = 2;

try {
  let a = 2 + b;
} catch (erro) {
  console.log(erro);
} finally {
  console.log("Executou");
}

// console.log("Teste");
